id = "soma"
name = "Soma"
version = "0.2.0"
schema_version = 1
authors = ["Gabriel <gabriel@minatel.dev>"]
description = "Syntax highlighting and LSP support for the Soma programming language."
repository = "https://github.com/srgaabriel/soma"

[grammars.soma]
repository = "https://github.com/srgaabriel/tree-sitter-soma"
rev = "4dd0f9ffee7455d8a5985c58fa2c2a537b7ec80a"
